spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://edmindev:mldnjava@eureka-7001.com:7001/eureka
  instance:
    #lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔
    #lease-expiration-duration-in-seconds: 5 # 默认90秒 超过5秒为挂掉
    instance-id: dept-8001.com   #在信息列表显示主机名称
    prefer-ip-address: true        #访问路径变为ip地址

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.mldn.vo
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml 
spring:
  profiles: dev
  messages:
    basename: i18n/Messages,i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/mldn8001
    username: root
    password: mysqladmin
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  application:
    name: microcloud-config-dept-client # 实例所在主机名称
---
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://edminbeta:mldnjava@eureka-7001.com:7001/eureka
  instance:
    #lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔
    #lease-expiration-duration-in-seconds: 5 # 默认90秒 超过5秒为挂掉
    instance-id: dept-8001.com   #在信息列表显示主机名称
    prefer-ip-address: true        #访问路径变为ip地址

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: cn.mldn.vo
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml 
spring:
  profiles: dev
  messages:
    basename: i18n/Messages,i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/mldn8001
    username: root
    password: mysqladmin
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  application:
    name: microcloud-config-dept-client # 实例所在主机名称
      
    